# Generated by Django 5.2.7 on 2025-11-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(db_index=True, help_text='Line User ID', max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='使用者暱稱')),
                ('member_code', models.CharField(max_length=10, unique=True, verbose_name='會員代號')),
                ('member_type', models.PositiveSmallIntegerField(choices=[(1, '一般會員'), (2, '付費會員')], default=1, help_text='會員類型', verbose_name='會員類型')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '啟用'), (2, '停用')], default=1, help_text='帳號是否啟用', verbose_name='帳號狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者列表',
                'db_table': 'users',
            },
        ),
    ]
