repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace      # 移除行尾空格
      - id: end-of-file-fixer        # 確保檔案結尾有換行
      - id: mixed-line-ending        # 統一換行符號
