# Generated by Django 6.0.1 on 2026-04-14 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_friendship_prevent_self_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(db_index=True, max_length=7, verbose_name='年月')),
                ('total_api_calls', models.IntegerField(default=0, verbose_name='總 API 呼叫次數')),
                ('search_calls', models.IntegerField(default=0, verbose_name='搜尋 API 次數')),
                ('detail_calls', models.IntegerField(default=0, verbose_name='詳細資訊 API 次數')),
                ('can_use', models.BooleanField(default=True, verbose_name='是否可使用')),
                ('monthly_limit', models.IntegerField(default=100, verbose_name='當月額度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_records', to='users.user', verbose_name='使用者')),
            ],
            options={
                'verbose_name': 'API 使用記錄',
                'verbose_name_plural': 'API 使用記錄列表',
                'db_table': 'api_usage_records',
                'ordering': ['-year_month'],
                'unique_together': {('user', 'year_month')},
            },
        ),
    ]
