# Generated by Django 6.0.1 on 2026-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagerecord',
            name='ai_calls',
            field=models.IntegerField(default=0, verbose_name='AI API 次數'),
        ),
        migrations.AddField(
            model_name='apiusagerecord',
            name='can_use_ai',
            field=models.BooleanField(default=True, verbose_name='是否可使用 AI'),
        ),
        migrations.AddField(
            model_name='apiusagerecord',
            name='monthly_ai_limit',
            field=models.IntegerField(default=50, verbose_name='當月 AI 額度'),
        ),
    ]
