# Generated by Django 5.2.7 on 2025-11-13 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Google Place ID')),
                ('name', models.CharField(max_length=200, verbose_name='咖啡店名稱')),
                ('address', models.TextField(max_length=300, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Google 評分')),
                ('user_ratings_total', models.IntegerField(default=0, verbose_name='評論數量')),
                ('opening_hours', models.JSONField(blank=True, default=list, verbose_name='營業時間')),
                ('website', models.URLField(blank=True, null=True, verbose_name='官方網站')),
                ('google_maps', models.URLField(blank=True, null=True, verbose_name='Google Maps 連結')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏數')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '咖啡店',
                'verbose_name_plural': '咖啡店列表',
                'db_table': 'cafes',
                'indexes': [models.Index(fields=['place_id'], name='cafes_place_i_d4344b_idx'), models.Index(fields=['-favorite_count'], name='cafes_favorit_970090_idx'), models.Index(fields=['lat', 'lng'], name='cafes_lat_93d1ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='個人備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='line_bot.cafe', verbose_name='咖啡店')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='line_bot.user', verbose_name='使用者')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏列表',
                'db_table': 'favorites',
                'unique_together': {('user', 'cafe')},
            },
        ),
    ]
