# Generated by Django 5.2.7 on 2025-11-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0002_cafe_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開收藏'),
        ),
    ]
