# Generated by Django 5.2.7 on 2025-11-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0003_favorite_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='opening_hours',
            field=models.TextField(blank=True, default=list, verbose_name='營業時間'),
        ),
    ]
