# Generated by Django 5.2.7 on 2025-11-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0004_alter_cafe_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, verbose_name='營業時間'),
        ),
    ]
