# Generated by Django 5.2.7 on 2025-11-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cafe',
            name='cafes_place_i_d4344b_idx',
        ),
    ]
