# Generated by Django 5.2.7 on 2025-12-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_remove_cafe_cafes_place_i_d4344b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='photo_reference',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cafe',
            name='photo_s3_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
