# Generated by Django 5.2.7 on 2026-01-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_remove_cafe_cafes_place_i_d4344b_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='has_plug',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='is_time_unlimited',
        ),
        migrations.AddField(
            model_name='cafe',
            name='attributes_last_calculated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='has_socket',
            field=models.CharField(blank=True, choices=[('no', '很少或沒有'), ('maybe', '視座位'), ('yes', '很多')], max_length=10, null=True, verbose_name='是否有插座'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='limited_time',
            field=models.CharField(blank=True, choices=[('no', '一律不限時'), ('maybe', '視情況限時'), ('yes', '一律限時')], max_length=10, null=True, verbose_name='是否限時'),
        ),
    ]
