# Generated by Django 5.2.7 on 2025-12-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_cafe_photo_reference_cafe_photo_s3_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='photo_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='照片更新時間'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='photo_reference',
            field=models.CharField(blank=True, default='', verbose_name='Google Photo Reference'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='photo_s3_url',
            field=models.URLField(blank=True, default='', verbose_name='S3 照片 URL'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='瀏覽次數'),
        ),
    ]
