# Generated by Django 5.2.7 on 2026-01-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_remove_cafe_has_plug_remove_cafe_is_time_unlimited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='經度'),
        ),
    ]
