# Generated by Django 5.2.7 on 2026-01-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_alter_cafe_lat_alter_cafe_lng'),
        ('users', '0003_friendship_prevent_self_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeAttributeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('socket', '插座'), ('limited_time', '限時'), ('cheap', '價格'), ('quiet', '安靜')], max_length=20, verbose_name='屬性類型')),
                ('value', models.CharField(choices=[('yes', '是/有'), ('no', '否/無'), ('maybe', '可能/部分'), ('unknown', '未知')], max_length=20, verbose_name='屬性值')),
                ('source', models.CharField(choices=[('user', '使用者回報'), ('cafenomad', 'CafeNomad API'), ('inferred', '系統推論')], max_length=20, verbose_name='資料來源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_votes', to='cafe.cafe', verbose_name='咖啡店')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='回報使用者')),
            ],
            options={
                'verbose_name': '咖啡店屬性投票',
                'verbose_name_plural': '咖啡店屬性投票',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cafe', 'attribute'], name='cafe_cafeat_cafe_id_1e12c0_idx'), models.Index(fields=['created_at'], name='cafe_cafeat_created_7d3de0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('cafe', 'attribute', 'user'), name='unique_user_vote_per_attribute')],
            },
        ),
    ]
