# Generated by Django 5.2.7 on 2026-01-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_cafeattributevote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeNomadCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafenomad_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='CafeNomad ID')),
                ('name', models.CharField(max_length=200, verbose_name='店名')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='緯度')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='經度')),
                ('socket', models.CharField(blank=True, choices=[('yes', '很多'), ('no', '很少或沒有'), ('maybe', '視座位')], max_length=10, null=True, verbose_name='插座')),
                ('limited_time', models.CharField(blank=True, choices=[('yes', '一律限時'), ('no', '一律不限時'), ('maybe', '視情況限時')], max_length=10, null=True, verbose_name='是否限時')),
                ('standing_desk', models.CharField(blank=True, choices=[('yes', '有'), ('no', '無')], max_length=10, null=True, verbose_name='站立桌')),
                ('wifi', models.FloatField(blank=True, null=True, verbose_name='WiFi 穩定度')),
                ('seat', models.FloatField(blank=True, null=True, verbose_name='通常有位')),
                ('quiet', models.FloatField(blank=True, null=True, verbose_name='安靜程度')),
                ('tasty', models.FloatField(blank=True, null=True, verbose_name='咖啡好喝')),
                ('cheap', models.FloatField(blank=True, null=True, verbose_name='價格便宜')),
                ('music', models.FloatField(blank=True, null=True, verbose_name='裝潢音樂')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='官方網站')),
                ('mrt', models.CharField(blank=True, max_length=100, verbose_name='最近捷運站')),
                ('open_time', models.CharField(blank=True, max_length=200, verbose_name='營業時間')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='最後同步時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': 'CafeNomad 快取',
                'verbose_name_plural': 'CafeNomad 快取',
                'db_table': 'cafe_nomad_cache',
                'ordering': ['-synced_at'],
                'indexes': [models.Index(fields=['lat', 'lng'], name='idx_cafenomad_coords'), models.Index(fields=['city'], name='idx_cafenomad_city'), models.Index(fields=['synced_at'], name='idx_cafenomad_synced')],
            },
        ),
    ]
