# Generated by Django 6.0.1 on 2026-01-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_cafe_photo_updated_at_alter_cafe_photo_reference_and_more'),
        ('cafe', '0006_cafenomadcache'),
    ]

    operations = [
    ]
