# Generated by Django 6.0.1 on 2026-01-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_merge_20260119_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafenomadcache',
            name='limited_time',
            field=models.CharField(blank=True, choices=[('no', '一律不限時'), ('maybe', '視情況限時'), ('yes', '一律限時')], max_length=10, null=True, verbose_name='是否限時'),
        ),
        migrations.AlterField(
            model_name='cafenomadcache',
            name='socket',
            field=models.CharField(blank=True, choices=[('no', '很少或沒有'), ('maybe', '視座位'), ('yes', '很多')], max_length=10, null=True, verbose_name='插座'),
        ),
    ]
