# Generated by Django 6.0.1 on 2026-04-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_alter_cafenomadcache_limited_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeattributevote',
            name='source',
            field=models.CharField(choices=[('user', '使用者回報'), ('cafenomad', 'CafeNomad API'), ('google', 'Google Places API'), ('inferred', '系統推論')], max_length=20, verbose_name='資料來源'),
        ),
    ]
