# Generated by Django 6.0.1 on 2026-04-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_alter_cafenomadcache_limited_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='has_pet',
            field=models.CharField(blank=True, choices=[('no', '沒有'), ('maybe', '有時有'), ('yes', '有貓貓狗狗')], max_length=10, null=True, verbose_name='店內有貓貓狗狗'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='pet_friendly',
            field=models.CharField(blank=True, choices=[('no', '不歡迎寵物'), ('maybe', '視情況'), ('yes', '歡迎寵物')], max_length=10, null=True, verbose_name='寵物友善'),
        ),
        migrations.AlterField(
            model_name='cafeattributevote',
            name='attribute',
            field=models.CharField(choices=[('socket', '插座'), ('limited_time', '限時'), ('cheap', '價格'), ('quiet', '安靜'), ('pet_friendly', '寵物友善'), ('has_pet', '有貓貓狗狗')], max_length=20, verbose_name='屬性類型'),
        ),
    ]
