# Generated by Django 6.0.1 on 2026-04-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_add_pet_friendly_has_pet'),
        ('cafe', '0009_alter_cafeattributevote_source'),
    ]

    operations = [
    ]
