# Generated by Django 6.0.1 on 2026-06-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_merge_20260418_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='reviews',
            field=models.JSONField(blank=True, default=list, verbose_name='用戶評論'),
        ),
    ]
