# Generated by Django 6.0.1 on 2026-06-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_add_reviews_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='reviews',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='用戶評論'),
        ),
    ]
